import { NextResponse } from "next/server";
import OpenAI from "openai";
import { validatePromptInput } from "@/lib/validation";
import { JengaPromptsInput, JengaPromptsOutput } from "@/lib/types";

// Check for OpenAI API key at module initialization
if (!process.env.OPENAI_API_KEY) {
  throw new Error("OPENAI_API_KEY is not set. Please add it to your .env.local file.");
}

// Initialize OpenAI with API key from environment variable
const openai = new OpenAI({
  apiKey: process.env.OPENAI_API_KEY,
});

// Function to call OpenAI API and process the response
async function callOpenAI(data: JengaPromptsInput): Promise<JengaPromptsOutput> {
  console.log("Calling OpenAI API with data:", JSON.stringify(data));

  try {
    const response = await openai.chat.completions.create({
      model: "gpt-4o-mini",
      messages: [
        {
          role: "user",
          content: `Enhance the following prompt according to the selected mode:
          Core Idea: "${data.corePromptIdea}"
          Prompt Mode: "${data.promptMode}"
          Modifiers: ${JSON.stringify(data.modifiers)}
          
          Please provide the output in the following structure: ${data.outputStructure}`,
        },
      ],
      tools: [
        {
          type: "function",
          function: {
            name: "enhance_prompt",
            description: "Enhance the given prompt based on user inputs and modifiers",
            parameters: {
              type: "object",
              properties: {
                enhancedPrompt: {
                  type: "string",
                  description: "The enhanced prompt generated by the model",
                },
                additionalInfo: {
                  type: "object",
                  description: "Any additional structured information if requested",
                },
              },
              required: ["enhancedPrompt"],
            },
          },
        },
      ],
      tool_choice: {"type": "function", "function": {"name": "enhance_prompt"}},
    });

    console.log("Received response from OpenAI API:", JSON.stringify(response));

    const toolCalls = response.choices[0].message.tool_calls;
    if (toolCalls && toolCalls[0].function.name === "enhance_prompt") {
      const output = JSON.parse(toolCalls[0].function.arguments);
      console.log("Parsed OpenAI response output:", JSON.stringify(output));
      return {
        primaryResult: output.enhancedPrompt,
        structuredJSON: output.additionalInfo,
      };
    }

    // Fallback for cases where the model returns a message directly
    if (response.choices[0].message.content) {
      return {
        primaryResult: response.choices[0].message.content,
      };
    }

    throw new Error("Unexpected response structure from OpenAI API");
  } catch (error) {
    console.error("Error while calling OpenAI API:", error);
    throw error;
  }
}

export async function POST(req: Request) {
  console.log("Received POST request");

  try {
    // Parse the incoming JSON request body
    const rawData = await req.json();
    console.log("Parsed request data:", JSON.stringify(rawData));

    // Validate the input data
    const data = validatePromptInput(rawData);

    // Validate that the selected output format is supported
    if (!["Descriptive Paragraph", "Simple JSON", "Detailed JSON"].includes(data.outputStructure)) {
      throw new Error("Invalid output structure selected.");
    }

    // Validate prompt modes and adjust modifiers accordingly
    if (data.promptMode === 'Image') {
      if (!data.modifiers.style || !data.modifiers.aspectRatio) {
        throw new Error("Style and Aspect Ratio are required for Image mode.");
      }
    }

    // Call OpenAI API to get the enhanced prompt
    const result = await callOpenAI(data);
    console.log("Prompt enhancement completed successfully");

    // Return the structured response
    return NextResponse.json(result, { status: 200 });
  } catch (error) {
    console.error("Error in POST handler:", error);
    
    // Handle validation errors specifically
    if (error instanceof Error && error.name === 'ZodError') {
      return NextResponse.json(
        {
          error: "Invalid input data.",
          details: error.message,
        },
        { status: 400 }
      );
    }
    
    return NextResponse.json(
      {
        error: "Failed to enhance prompt.",
        details: error instanceof Error ? error.message : String(error),
      },
      { status: 500 }
    );
  }
}

// OPTIONS requests are handled by middleware.ts